### ISSUE TITLE
rename module to `fastapi-openid-utils`

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/eoapi-auth-utils#5]
This module might not be useful only for eoapi, but if I understand well, could be useful for other project using OpenID auth

**Comment by alukach** [comment]
I had considered that this might be generally useful; however, as it currently stands, this module is targeted toward applying standard auth patterns to FastAPI applications with pre-built endpoints. That is a need I have only seen within eoAPI-type applications. I would generally recommend _not_ using this module/pattern for any typical FastAPI application, as there are more straight-forward strategies with [built-in FastAPI tooling](https://fastapi.tiangolo.com/tutorial/security/#openid-connect).

Additionally, this is just the beginning of the module; its scope will likely expand quickly to provide more auth patterns targeted for eoAPI's needs. I recommend we continue with this primarily targeting eoAPI, and if the opportunity presents itself, we can generalize or separate into names/modules that would benefit larger audiences.
